### ISSUE TITLE
Shadow can’t be disabled

### ISSUE THREAD

**Issue by ldidry** [Psycojoker/sticker_bordure#4]
Gimp: 2.10.12-1
Gimp-python: 2.10.8-2+b1
Python: 2.7.17-2

Even if I toggle the option off, it has no effect, the shadow under the sticker is always added.

It previously worked while I used the 8671600e1071e998518344b04e34bc9b162aec57 version of the plug-in.

**Comment by jversusk** [comment]
I don't think it's a problem with the shadow alone, it seems all the values were being passed incorrectly after a change in the order of the settings. Try changing this line:
https://github.com/Psycojoker/sticker_bordure/blob/9e3d58e37aaf67d969f43e62e757419e33bd0e5c/stickers_bordure.py#L7
to:
`def stickerify_bordure(image, current_layer, resize=False, black_grow=3, white_grow=12, shadow=True, canvas_increase=0):`

**Comment by Psycojoker** [comment]
Should be fixed now, thx for your patch :)
